import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useCounterStore, useRootStore } from '@providers/RootStoreProvider';
import { observer } from 'mobx-react-lite'

const Home: NextPage = observer(() => {
  const rootStore = useRootStore();
  const counterStore = useCounterStore();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          COUNTER with MOBX
        </h1>

        {/* <h2>Is user logged in? {rootStore.isLoggedIn ? 'YES' : 'NOPE'}</h2>
        <button onClick={() => rootStore.toggleIsLoggedIn()}>TOGGLE!</button> */}

        <div>
          Count : {counterStore.counter}<br />
          State : {counterStore.status}
        </div>

        <div>
          <button onClick={() => counterStore.start()}>START COUNTING</button>
          <button onClick={() => counterStore.pause()}>PAUSE~</button>
          <button onClick={() => counterStore.stop()}>STOP!</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
})

export default Home
